# Make and run executable
all: make run

# Create executable for Program 
make: aliasing.c
	gcc -o aliasing aliasing.c

# Run executable
run: aliasing
	./aliasing

#Debugging Code
edit: aliasing.c
	vim aliasing.c
	
# Clean Folder up
clean: 
	rm aliasing
