# Make and run executable
all: make run

# Create executable for Program 
make: aliasing.c
	gcc -o aliasing aliasing.c

# Run executable
run: aliasing
	./aliasing

# Clean Folder up
clean: 
	rm aliasing
